name: "Comment run"

on:
  issue_comment: 
    types: [created, edited]
    
jobs:
  comment-run:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/')
    steps:
    - name: say hello
      if: contains(github.event.comment.body, '/support')
      run: |
        echo say hello
    - name: test
      if: contains(github.event.comment.body, '/test')
      run: |
        echo test
